### ISSUE TITLE
搜狗输入法键盘遮挡问题

### ISSUE THREAD

**Issue by wushenchao** [LeoiOS/LCProgressHUD#1]
5s上面当使用搜狗输入法输入时，存在键盘遮挡问题

**Comment by iTofu** [comment]
请问是键盘挡住了 HUD，还是 HUD 挡住了键盘？

**Comment by wushenchao** [comment]
键盘遮挡了HUD

**Comment by iTofu** [comment]
看使用场景吧，大多数情况下显示 HUD 的时候都是让用户等待某个进程（Loading）或者获取操作结果（Success、Failure），这些场景下一般而言不会让用户输入，也就是讲不会显示键盘。如果你有需求，使用 MBProgressHUD 监听键盘事件做一下吧。
